version: '3'

services:
  db:
    image: "postgres:11.4"
    container_name: "postgres-database"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-database:/var/lib/postgresql/data
volumes:
  postgres-database:

